import type { IconType } from "react-icons";
import {
  MdAdd,
  MdAddBox,
  MdAllInclusive,
  MdAutoStories,
  MdSmartDisplay,
  MdArrowBack,
  MdArrowForward,
  MdAssignment,
  MdBadge,
  MdBarChart,
  MdBlock,
  MdBusiness,
  MdBusinessCenter,
  MdCalendarMonth,
  MdCall,
  MdCategory,
  MdCheck,
  MdCheckCircle,
  MdChevronRight,
  MdCloudUpload,
  MdCode,
  MdDashboard,
  MdDelete,
  MdDescription,
  MdDoNotDisturbOn,
  MdDomainAdd,
  MdDownload,
  MdEdit,
  MdEvent,
  MdEventAvailable,
  MdEventBusy,
  MdExplore,
  MdFactCheck,
  MdFilterAlt,
  MdFormatListBulleted,
  MdFormatListNumbered,
  MdFormatQuote,
  MdUndo,
  MdRedo,
  MdGroups,
  MdHandshake,
  MdHub,
  MdInbox,
  MdInfo,
  MdInsights,
  MdLanguage,
  MdLaptop,
  MdLightbulb,
  MdLink,
  MdLocationOn,
  MdLogout,
  MdMail,
  MdMenu,
  MdMenuBook,
  MdMoreVert,
  MdNotifications,
  MdNotificationsActive,
  MdPerson,
  MdPersonAdd,
  MdPersonSearch,
  MdPictureAsPdf,
  MdPlayArrow,
  MdPostAdd,
  MdPriorityHigh,
  MdAutorenew,
  MdPhotoCamera,
  MdQuiz,
  MdRadioButtonUnchecked,
  MdRateReview,
  MdRemove,
  MdReplay,
  MdRocketLaunch,
  MdSave,
  MdSchedule,
  MdSchool,
  MdSearch,
  MdSearchOff,
  MdSend,
  MdSentimentDissatisfied,
  MdSettings,
  MdStar,
  MdThumbUp,
  MdTimer,
  MdTrackChanges,
  MdTranslate,
  MdTrendingUp,
  MdUpload,
  MdVerified,
  MdVerifiedUser,
  MdVideoCall,
  MdVisibility,
  MdVisibilityOff,
  MdWarning,
  MdWork,
  MdWorkHistory,
  MdWorkspacePremium,
  MdCelebration,
  MdClose,
} from "react-icons/md";
import { cn } from "@/lib/utils";

/**
 * Icon registry — maps the semantic names used across the app to react-icons
 * (Material Design set). Keeping the string API means components stay decoupled
 * from the underlying icon library.
 */
const ICONS: Record<string, IconType> = {
  add: MdAdd,
  add_box: MdAddBox,
  all_inclusive: MdAllInclusive,
  auto_stories: MdAutoStories,
  smart_display: MdSmartDisplay,
  arrow_back: MdArrowBack,
  arrow_forward: MdArrowForward,
  assignment: MdAssignment,
  badge: MdBadge,
  bar_chart: MdBarChart,
  block: MdBlock,
  business: MdBusiness,
  business_center: MdBusinessCenter,
  calendar_month: MdCalendarMonth,
  call: MdCall,
  category: MdCategory,
  celebration: MdCelebration,
  check: MdCheck,
  check_circle: MdCheckCircle,
  chevron_right: MdChevronRight,
  close: MdClose,
  cloud_upload: MdCloudUpload,
  code: MdCode,
  dashboard: MdDashboard,
  delete: MdDelete,
  description: MdDescription,
  do_not_disturb_on: MdDoNotDisturbOn,
  domain_add: MdDomainAdd,
  download: MdDownload,
  edit: MdEdit,
  event: MdEvent,
  event_available: MdEventAvailable,
  event_busy: MdEventBusy,
  explore: MdExplore,
  fact_check: MdFactCheck,
  filter_alt: MdFilterAlt,
  format_list_bulleted: MdFormatListBulleted,
  format_list_numbered: MdFormatListNumbered,
  format_quote: MdFormatQuote,
  undo: MdUndo,
  redo: MdRedo,
  groups: MdGroups,
  handshake: MdHandshake,
  hub: MdHub,
  inbox: MdInbox,
  info: MdInfo,
  insights: MdInsights,
  language: MdLanguage,
  laptop: MdLaptop,
  lightbulb: MdLightbulb,
  link: MdLink,
  location_on: MdLocationOn,
  logout: MdLogout,
  mail: MdMail,
  menu: MdMenu,
  menu_book: MdMenuBook,
  more_vert: MdMoreVert,
  notifications: MdNotifications,
  notifications_active: MdNotificationsActive,
  person: MdPerson,
  person_add: MdPersonAdd,
  person_search: MdPersonSearch,
  picture_as_pdf: MdPictureAsPdf,
  play_arrow: MdPlayArrow,
  post_add: MdPostAdd,
  priority_high: MdPriorityHigh,
  progress_activity: MdAutorenew,
  photo_camera: MdPhotoCamera,
  quiz: MdQuiz,
  radio_button_unchecked: MdRadioButtonUnchecked,
  rate_review: MdRateReview,
  remove: MdRemove,
  replay: MdReplay,
  rocket_launch: MdRocketLaunch,
  save: MdSave,
  schedule: MdSchedule,
  school: MdSchool,
  search: MdSearch,
  search_off: MdSearchOff,
  send: MdSend,
  sentiment_dissatisfied: MdSentimentDissatisfied,
  settings: MdSettings,
  star: MdStar,
  target: MdTrackChanges,
  thumb_up: MdThumbUp,
  timer: MdTimer,
  translate: MdTranslate,
  trending_up: MdTrendingUp,
  upload: MdUpload,
  verified: MdVerified,
  verified_user: MdVerifiedUser,
  video_call: MdVideoCall,
  visibility: MdVisibility,
  visibility_off: MdVisibilityOff,
  warning: MdWarning,
  work: MdWork,
  work_history: MdWorkHistory,
  workspace_premium: MdWorkspacePremium,
};

interface IconProps {
  /** Semantic icon name from the registry above, e.g. "work", "school", "check". */
  name: string;
  /** Kept for API compatibility (Material Design icons are filled by default). */
  filled?: boolean;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * Renders an SVG icon that inherits `color` (via currentColor) and `font-size`
 * (icons are sized in `em`), so Tailwind `text-*` utilities control size and color.
 */
export function Icon({ name, className, style }: IconProps) {
  const Glyph = ICONS[name] ?? MdInfo;
  // Default to 20px; any `text-[size]` passed in className overrides via twMerge.
  return <Glyph aria-hidden className={cn("inline-block shrink-0 text-xl", className)} style={style} />;
}
